version: '3.4'

services:
  cartapi.service:
    image: cartapiservice
    build:
      dockerfile: Dockerfile
    environment:
      CartApi__ConnectionString: 'server=192.168.1.120;port=5433;database=cartapi;uid=postgres;password=postgres;'
    ports:
      - 5007:80
